### ISSUE TITLE
Update Longshot certificates with Let's Encrypt.

### ISSUE THREAD

**Issue by blisteringherb** [DoSomething/infrastructure#118]
I've set up the cert updating on HAProxy using Let's Encrypt in the same way as it's set up for HRBlock.  Here are the commands I ran:  

```  
sudo certbot certonly --standalone -d www.footlockerscholarathletes.com -d footlockerscholarathletes.com \
    --non-interactive --agree-tos --email devops@dosomething.org \
    --http-01-port=8888
```  

`sudo mkdir -p /etc/ssl/www.footlockerscholarathletes.com`  

```  
sudo cat /etc/letsencrypt/live/www.footlockerscholarathletes.com/fullchain.pem \
    /etc/letsencrypt/live/www.footlockerscholarathletes.com/privkey.pem \
    | sudo tee /etc/ssl/www.footlockerscholarathletes.com/www.footlockerscholarathletes.com.pem  
```    

Added to `/opt/update-certs.sh` which gets run by cron every month so certs are updated each month:  
```
bash -c "cat /etc/letsencrypt/live/www.footlockerscholarathletes.com/fullchain.pem /etc/letsencrypt/live/www.footlockerscholarathletes.com/privkey.pem > /etc/ssl/www.footlockerscholarathletes.com/www.footlockerscholarathletes.com.pem"  
```  

Here's the current info for certificates being renewed by Let's Encrypt:  
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: www.footlockerscholarathletes.com
    Domains: www.footlockerscholarathletes.com footlockerscholarathletes.com
    Expiry Date: 2019-04-22 22:45:11+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/www.footlockerscholarathletes.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/www.footlockerscholarathletes.com/privkey.pem
  Certificate Name: caps.hrblock.com
    Domains: caps.hrblock.com
    Expiry Date: 2019-04-01 04:00:08+00:00 (VALID: 68 days)
    Certificate Path: /etc/letsencrypt/live/caps.hrblock.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/caps.hrblock.com/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by DFurnes** [comment]
We've been getting [daily ACM failures for these two apps](https://dosomething.slack.com/archives/C03T8SDMW/p1549292714003400) since shortly after this change was made. I wonder if it's perhaps because ACM is also backed by Let's Encrypt, and so the Let's Encrypt certificate authority is (reasonably) refusing to grant two simultaneous certs for the same domain?

It might be worth trying configuring the Heroku SSL certificates for these two apps manually, since we get the private key & public cert. Since these change out frequently, we can add a step to your `update-certs.sh` script to set these on each application with `heroku certs:update`.

**Comment by DFurnes** [comment]
Closing this. Referenced in [#165497441](https://www.pivotaltracker.com/story/show/165497441).
