### ISSUE TITLE
Welcome Home campaign not loading

### ISSUE THREAD

**Issue by ngjo** [DoSomething/infrastructure#33]
_BUG_
-------------------
#### Current Behavior
https://www.dosomething.org/us/campaigns/welcome-home?source=node/1141 doesn't load 

(working theory from @DFurnes is that this was closed and he only grabbed active campaigns!)

#### Desired Behavior
https://www.dosomething.org/us/campaigns/welcome-home?source=node/1141 should load

#### Steps to Replicate
Go to https://www.dosomething.org/us/campaigns/welcome-home?source=node/1141 and see that it doesn't load

#### Why This Matters
Bc it's on the homepage

**Comment by DFurnes** [comment]
Oh, haha. It's because we have two campaigns nodes for this campaign: [`welcome-home-0`](https://www.dosomething.org/us/node/1662/edit) (which was originally activate, and [directed to Ashes](https://github.com/DoSomething/infrastructure/blob/3f293cd4d62073e5be0e9160f081250382e6b20b/dosomething/fastly-frontend/ashes_init.vcl#L300)), and [`welcome-home`](https://www.dosomething.org/us/node/34/edit) (which was then unpublished). Not really sure why we have both, but it's easy enough to add the new one as well.

**Comment by DFurnes** [comment]
Fixed in #34.

@mirie May be worth flagging for Krista (and making a call which to keep) when migrating these over. And we can always merge the two campaign IDs (alongside the runs) in Rogue later on down the road.
